# Generated by Django 5.1.7 on 2025-03-08 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('aircraft_registration', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('aircraft_type', models.CharField(max_length=50)),
                ('seating_capacity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('flight_identifier', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('flight_date', models.DateField()),
                ('departure_station', models.CharField(max_length=10)),
                ('scheduled_time_of_departure', models.DateTimeField()),
                ('arrival_station', models.CharField(max_length=10)),
                ('scheduled_time_of_arrival', models.DateTimeField()),
                ('aircraft_type', models.CharField(max_length=50)),
                ('physical_seating_capacity', models.PositiveIntegerField()),
                ('minimum_ground_time', models.PositiveIntegerField(help_text='Ground time in minutes')),
                ('onward_flight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_flights', to='api.flight')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='api.aircraft')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='api.flight')),
            ],
        ),
        migrations.CreateModel(
            name='PreAssignment',
            fields=[
                ('preassignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('description', models.CharField(max_length=255)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preassignments', to='api.aircraft')),
            ],
        ),
        migrations.AddConstraint(
            model_name='flight',
            constraint=models.UniqueConstraint(fields=('flight_identifier', 'flight_date'), name='unique_flight_per_day'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.UniqueConstraint(fields=('flight', 'aircraft'), name='unique_flight_aircraft_assignment'),
        ),
    ]
